//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamCmdPalExtension.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamCmdPalExtension.Properties.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Application 的本地化字符串。
        /// </summary>
        internal static string appType_application {
            get {
                return ResourceManager.GetString("appType_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beta 的本地化字符串。
        /// </summary>
        internal static string appType_beta {
            get {
                return ResourceManager.GetString("appType_beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comic 的本地化字符串。
        /// </summary>
        internal static string appType_comic {
            get {
                return ResourceManager.GetString("appType_comic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config 的本地化字符串。
        /// </summary>
        internal static string appType_config {
            get {
                return ResourceManager.GetString("appType_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Demo 的本地化字符串。
        /// </summary>
        internal static string appType_demo {
            get {
                return ResourceManager.GetString("appType_demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depot Only 的本地化字符串。
        /// </summary>
        internal static string appType_depotonly {
            get {
                return ResourceManager.GetString("appType_depotonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media (Deprecated) 的本地化字符串。
        /// </summary>
        internal static string appType_deprecatedMedia {
            get {
                return ResourceManager.GetString("appType_deprecatedMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DLC 的本地化字符串。
        /// </summary>
        internal static string appType_dlc {
            get {
                return ResourceManager.GetString("appType_dlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver 的本地化字符串。
        /// </summary>
        internal static string appType_driver {
            get {
                return ResourceManager.GetString("appType_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Franchise 的本地化字符串。
        /// </summary>
        internal static string appType_franchise {
            get {
                return ResourceManager.GetString("appType_franchise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 的本地化字符串。
        /// </summary>
        internal static string appType_game {
            get {
                return ResourceManager.GetString("appType_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guide 的本地化字符串。
        /// </summary>
        internal static string appType_guide {
            get {
                return ResourceManager.GetString("appType_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware 的本地化字符串。
        /// </summary>
        internal static string appType_hardware {
            get {
                return ResourceManager.GetString("appType_hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media (Legacy) 的本地化字符串。
        /// </summary>
        internal static string appType_legacyMedia {
            get {
                return ResourceManager.GetString("appType_legacyMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music 的本地化字符串。
        /// </summary>
        internal static string appType_music {
            get {
                return ResourceManager.GetString("appType_music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin 的本地化字符串。
        /// </summary>
        internal static string appType_plugin {
            get {
                return ResourceManager.GetString("appType_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series 的本地化字符串。
        /// </summary>
        internal static string appType_series {
            get {
                return ResourceManager.GetString("appType_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcut 的本地化字符串。
        /// </summary>
        internal static string appType_shortcut {
            get {
                return ResourceManager.GetString("appType_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool 的本地化字符串。
        /// </summary>
        internal static string appType_tool {
            get {
                return ResourceManager.GetString("appType_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video 的本地化字符串。
        /// </summary>
        internal static string appType_video {
            get {
                return ResourceManager.GetString("appType_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SteamPal 的本地化字符串。
        /// </summary>
        internal static string displayName {
            get {
                return ResourceManager.GetString("displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available for Free 的本地化字符串。
        /// </summary>
        internal static string displayStatus_availForFree {
            get {
                return ResourceManager.GetString("displayStatus_availForFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available Guest Pass 的本地化字符串。
        /// </summary>
        internal static string displayStatus_availGuestPass {
            get {
                return ResourceManager.GetString("displayStatus_availGuestPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available to Borrow 的本地化字符串。
        /// </summary>
        internal static string displayStatus_availToBorrow {
            get {
                return ResourceManager.GetString("displayStatus_availToBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Borrower Locked 的本地化字符串。
        /// </summary>
        internal static string displayStatus_borrowerLocked {
            get {
                return ResourceManager.GetString("displayStatus_borrowerLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CloudError 的本地化字符串。
        /// </summary>
        internal static string displayStatus_cloudError {
            get {
                return ResourceManager.GetString("displayStatus_cloudError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CloudOutOfDate 的本地化字符串。
        /// </summary>
        internal static string displayStatus_cloudOutOfDate {
            get {
                return ResourceManager.GetString("displayStatus_cloudOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Disabled 的本地化字符串。
        /// </summary>
        internal static string displayStatus_downloadDisabled {
            get {
                return ResourceManager.GetString("displayStatus_downloadDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading 的本地化字符串。
        /// </summary>
        internal static string displayStatus_downloading {
            get {
                return ResourceManager.GetString("displayStatus_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Paused 的本地化字符串。
        /// </summary>
        internal static string displayStatus_downloadPaused {
            get {
                return ResourceManager.GetString("displayStatus_downloadPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Queued 的本地化字符串。
        /// </summary>
        internal static string displayStatus_downloadQueued {
            get {
                return ResourceManager.GetString("displayStatus_downloadQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Required 的本地化字符串。
        /// </summary>
        internal static string displayStatus_downloadRequired {
            get {
                return ResourceManager.GetString("displayStatus_downloadRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installing 的本地化字符串。
        /// </summary>
        internal static string displayStatus_installing {
            get {
                return ResourceManager.GetString("displayStatus_installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid 的本地化字符串。
        /// </summary>
        internal static string displayStatus_invalid {
            get {
                return ResourceManager.GetString("displayStatus_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Platform 的本地化字符串。
        /// </summary>
        internal static string displayStatus_invalidPlatform {
            get {
                return ResourceManager.GetString("displayStatus_invalidPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launching 的本地化字符串。
        /// </summary>
        internal static string displayStatus_launching {
            get {
                return ResourceManager.GetString("displayStatus_launching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LicenseExpired 的本地化字符串。
        /// </summary>
        internal static string displayStatus_licenseExpired {
            get {
                return ResourceManager.GetString("displayStatus_licenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License Pending 的本地化字符串。
        /// </summary>
        internal static string displayStatus_licensePending {
            get {
                return ResourceManager.GetString("displayStatus_licensePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Launchable 的本地化字符串。
        /// </summary>
        internal static string displayStatus_notLaunchable {
            get {
                return ResourceManager.GetString("displayStatus_notLaunchable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Deprecated) Parental Blocked 的本地化字符串。
        /// </summary>
        internal static string displayStatus_parentalBlocked {
            get {
                return ResourceManager.GetString("displayStatus_parentalBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preload Complete 的本地化字符串。
        /// </summary>
        internal static string displayStatus_preloadComplete {
            get {
                return ResourceManager.GetString("displayStatus_preloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preload Only 的本地化字符串。
        /// </summary>
        internal static string displayStatus_preloadOnly {
            get {
                return ResourceManager.GetString("displayStatus_preloadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Presale Only 的本地化字符串。
        /// </summary>
        internal static string displayStatus_presaleOnly {
            get {
                return ResourceManager.GetString("displayStatus_presaleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchase 的本地化字符串。
        /// </summary>
        internal static string displayStatus_purchase {
            get {
                return ResourceManager.GetString("displayStatus_purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready to Install 的本地化字符串。
        /// </summary>
        internal static string displayStatus_readyToInstall {
            get {
                return ResourceManager.GetString("displayStatus_readyToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready to Launch 的本地化字符串。
        /// </summary>
        internal static string displayStatus_readyToLaunch {
            get {
                return ResourceManager.GetString("displayStatus_readyToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready to Preload 的本地化字符串。
        /// </summary>
        internal static string displayStatus_readyToPreload {
            get {
                return ResourceManager.GetString("displayStatus_readyToPreload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region Restricted 的本地化字符串。
        /// </summary>
        internal static string displayStatus_regionRestricted {
            get {
                return ResourceManager.GetString("displayStatus_regionRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        internal static string displayStatus_running {
            get {
                return ResourceManager.GetString("displayStatus_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Synchronizing 的本地化字符串。
        /// </summary>
        internal static string displayStatus_synchronizing {
            get {
                return ResourceManager.GetString("displayStatus_synchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terminating 的本地化字符串。
        /// </summary>
        internal static string displayStatus_terminating {
            get {
                return ResourceManager.GetString("displayStatus_terminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unavailable 的本地化字符串。
        /// </summary>
        internal static string displayStatus_unavailable {
            get {
                return ResourceManager.GetString("displayStatus_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstalling 的本地化字符串。
        /// </summary>
        internal static string displayStatus_uninstalling {
            get {
                return ResourceManager.GetString("displayStatus_uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Disabled 的本地化字符串。
        /// </summary>
        internal static string displayStatus_updateDisabled {
            get {
                return ResourceManager.GetString("displayStatus_updateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Paused 的本地化字符串。
        /// </summary>
        internal static string displayStatus_updatePaused {
            get {
                return ResourceManager.GetString("displayStatus_updatePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Queued 的本地化字符串。
        /// </summary>
        internal static string displayStatus_updateQueued {
            get {
                return ResourceManager.GetString("displayStatus_updateQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Required 的本地化字符串。
        /// </summary>
        internal static string displayStatus_updateRequired {
            get {
                return ResourceManager.GetString("displayStatus_updateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating 的本地化字符串。
        /// </summary>
        internal static string displayStatus_updating {
            get {
                return ResourceManager.GetString("displayStatus_updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validating 的本地化字符串。
        /// </summary>
        internal static string displayStatus_validating {
            get {
                return ResourceManager.GetString("displayStatus_validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hours 的本地化字符串。
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rapidly find games in your Steam library 的本地化字符串。
        /// </summary>
        internal static string initializedSubtitle {
            get {
                return ResourceManager.GetString("initializedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to initialize Steam client, check log for more details 的本地化字符串。
        /// </summary>
        internal static string initializeFailedSubtitle {
            get {
                return ResourceManager.GetString("initializeFailedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing... 的本地化字符串。
        /// </summary>
        internal static string initializingSubtitle {
            get {
                return ResourceManager.GetString("initializingSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Played 的本地化字符串。
        /// </summary>
        internal static string lastPlayed {
            get {
                return ResourceManager.GetString("lastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        internal static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play Time 的本地化字符串。
        /// </summary>
        internal static string playTime {
            get {
                return ResourceManager.GetString("playTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Two Weeks Play Time 的本地化字符串。
        /// </summary>
        internal static string playTimeLast2Weeks {
            get {
                return ResourceManager.GetString("playTimeLast2Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties... 的本地化字符串。
        /// </summary>
        internal static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search by Name 的本地化字符串。
        /// </summary>
        internal static string queryPlaceholder {
            get {
                return ResourceManager.GetString("queryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Steam client and search {0} in store 的本地化字符串。
        /// </summary>
        internal static string searchInStoreSubtitle {
            get {
                return ResourceManager.GetString("searchInStoreSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search in Steam 的本地化字符串。
        /// </summary>
        internal static string searchInStoreTitle {
            get {
                return ResourceManager.GetString("searchInStoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pipe (Not planned) (Placeholder) 的本地化字符串。
        /// </summary>
        internal static string setting_debuggerMode_choice_pipe {
            get {
                return ResourceManager.GetString("setting_debuggerMode_choice_pipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TCP 的本地化字符串。
        /// </summary>
        internal static string setting_debuggerMode_choice_tcp {
            get {
                return ResourceManager.GetString("setting_debuggerMode_choice_tcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Steam CEF debugger working mode (not implemented) 的本地化字符串。
        /// </summary>
        internal static string setting_debuggerMode_description {
            get {
                return ResourceManager.GetString("setting_debuggerMode_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debugger Mode 的本地化字符串。
        /// </summary>
        internal static string setting_debuggerMode_label {
            get {
                return ResourceManager.GetString("setting_debuggerMode_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set debugging port for Steam CEF, default to dynamic 的本地化字符串。
        /// </summary>
        internal static string setting_debuggerPort_description {
            get {
                return ResourceManager.GetString("setting_debuggerPort_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Optional) Debugger Port 的本地化字符串。
        /// </summary>
        internal static string setting_debuggerPort_label {
            get {
                return ResourceManager.GetString("setting_debuggerPort_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum number of results to display in results (suggest below 50) 的本地化字符串。
        /// </summary>
        internal static string setting_maxResult_description {
            get {
                return ResourceManager.GetString("setting_maxResult_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Results 的本地化字符串。
        /// </summary>
        internal static string setting_maxResult_label {
            get {
                return ResourceManager.GetString("setting_maxResult_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags 的本地化字符串。
        /// </summary>
        internal static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yesterday 的本地化字符串。
        /// </summary>
        internal static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
    }
}
